package com.ibm.btt.usecase.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.ContextFactory;
/** 
 * Class Generated by BTT Tool
 * Created since: 2012/08/12 11:59:12
 */
public class CM1op extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  
	  Context context=this.getContext();
		 context.getKeyedCollection().setDynamic(true);
		 for (int i = 0; i < 10; i++) {
			 if (i%2==0) {
				 
				 context.setValueAt("commonUserListOp."+i+".commonfirstName", "common name "+i);
				 context.setValueAt("topUserList."+i+".topfirstName", "");
				 
			}else {
				 context.setValueAt("topUserList."+i+".topfirstName", "top first name "+i);
				 context.setValueAt("commonUserListOp."+i+".commonfirstName", "");
			}
			 context.setValueAt("commonUserListOp."+i+".commonlastName", "lastname"+i);
			 context.setValueAt("topUserList."+i+".toplastName", "lastname"+i);
		}
		 setContext(context);
		 fireExitEvent("create");
}
  }

