package com.ibm.btt.usecase.op;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.ContextFactory;
/** 
 * Class Generated by BTT Tool
 * Created since: 2012/08/19 19:18:21
 */
public class CM5 extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  	Context context=this.getContext();
		 context.getKeyedCollection().setDynamic(true);
		 for (int i = 0; i < 10; i++) {
			 if (i<3) {
				 context.setValueAt("acountList."+i+".firstLastName", "firstLastName"+i);
				 context.setValueAt("acountList."+i+".secondLastName", "acountList"+i);
			}else if(i>=3 && i<7){
				 context.setValueAt("acountList."+i+".firstLastName", "firstLastName"+i);
				 context.setValueAt("acountList."+i+".secondLastName", "");
			}else {
				context.setValueAt("acountList."+i+".firstLastName", "");
				context.setValueAt("acountList."+i+".secondLastName", "acountList"+i);
			}
			 
		}
		
		 setContext(context);
		 fireExitEvent("createData");
  }
}
