package com.ibm.btt.usecase.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.ContextFactory;
/** 
 * Class Generated by BTT Tool
 * Created since: 2012/08/19 20:04:07
 */
public class CM5_2 extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  Context context=ContextFactory.currentContext();
		 context.getKeyedCollection().setDynamic(true);
		 for (int i = 0; i < 10; i++) {
			 if (i<3) {
				 context.setValueAt("acountList."+i+".firstLastName", "Galindo");
				 context.setValueAt("acountList."+i+".accountAge", 18);
				 context.setValueAt("acountList."+i+".accountBalance", (float)i+1999);
			}else if(i>=3 && i<7){
				 context.setValueAt("acountList."+i+".firstLastName", "firstLastName"+i);
				 context.setValueAt("acountList."+i+".accountAge",i*6);
				 context.setValueAt("acountList."+i+".accountBalance", (float)i+1999);
			}else {
				context.setValueAt("acountList."+i+".firstLastName", "Galindo");
				context.setValueAt("acountList."+i+".accountAge", 18);
				context.setValueAt("acountList."+i+".accountBalance", (float)i+1999);
			}
			 
		}
		
		 setContext(context);
		 fireExitEvent("createData");
  }
}
