package com.ibm.btt.usecase.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.ContextFactory;
/** 
 * Class Generated by BTT Tool
 * Created since: 2012/08/12 20:44:15
 */
public class CM6op extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  
	     Context context=this.getContext();
		 context.getKeyedCollection().setDynamic(true);
		 for (int i = 0; i < 10; i++) {
			 context.setValueAt("accountList."+i+".accountBalance", (float)100-i);
		}
		 
		 context.setValueAt("testName", "testName");
		 setContext(context);
		 fireExitEvent("create");

  }
}
