package com.ibm.btt.usecase.op;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.ContextFactory;
/** 
 * Class Generated by BTT Tool
 * Created since: 2012/08/24 17:34:00
 */
public class CreateInsuranceData extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  
	  	 Context context=ContextFactory.getContextNamed("CreateInsuranceDataCtx");
		 context.getKeyedCollection().setDynamic(true);
		 SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		 for (int i = 0; i < 10; i++) {
			Date theDate = sdf.parse("2013-08-1"+i);
			context.setValueAt("NormalInsuranceDataList."+i+".InsuranceNumber",i);
			context.setValueAt("NormalInsuranceDataList."+i+".InsuranceName","normal insurance name"+i);
			context.setValueAt("NormalInsuranceDataList."+i+".InsurancePrice",new BigDecimal(i));
			context.setValueAt("NormalInsuranceDataList."+i+".InsuranceDuration",theDate);
			
			
			context.setValueAt("VIPInsuranceDataList."+i+".InsuranceNumber",i);
			context.setValueAt("VIPInsuranceDataList."+i+".InsuranceName","vip insurance name"+i);
			context.setValueAt("VIPInsuranceDataList."+i+".InsurancePrice",new BigDecimal(i));
			context.setValueAt("VIPInsuranceDataList."+i+".InsuranceDuration",theDate);
		}
				
		 setContext(context);
		 fireExitEvent("insuranceList");
	  
	  
  }
}
