package com.ibm.btt.usecase.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.ContextFactory;
/** 
 * Class Generated by BTT Tool
 * Created since: 2012/08/13 00:05:08
 */
public class Mf2op extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  
	     Context context=this.getContext();
		 context.getKeyedCollection().setDynamic(true);
		 for (int i = 0; i < 10; i++) {
			 context.setValueAt("sampleUserList."+i+".Mf2opIndex",i);
			 context.setValueAt("sampleUserList."+i+".samplefirstName","samplefirstName" + i);
		}
		 
		 setContext(context);
		 fireExitEvent("create");

  }
}
