package com.ibm.btt.usecase.op;
import java.math.BigDecimal;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.ContextFactory;
/** 
 * Class Generated by BTT Tool
 * Created since: 2012/08/24 00:53:13
 */
public class saveMoneyOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  
	     Context context=ContextFactory.getContextNamed("saveMoneyOpCtx");
		 context.getKeyedCollection().setDynamic(true);
		 BigDecimal userAccount = (BigDecimal)context.getValueAt("userAccount");
		 BigDecimal saveMoney = (BigDecimal)context.getValueAt("saveMoney");
		 
		 if ( saveMoney != null && userAccount != null && (saveMoney.compareTo(new BigDecimal(0)) > 0)) {
				 
				 context.setValueAt("userAccount", userAccount.add(saveMoney) );
								 
			}
				
		 setContext(context);
		 fireExitEvent("saveSuccess");
}
  }

