package com.ibm.btt.test;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.ContextFactory;
/** 
 * Class Generated by BTT Tool
 * Created since: 2012/08/10 18:51:28
 */
public class CreateGlobal extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  	Context context=ContextFactory.currentContext();
		 context.getKeyedCollection().setDynamic(true);
		 for (int i = 0; i < 10; i++) {
			 context.setValueAt("CreateGlobalList."+i+".CreateGlobalData", 10-i);
		}
		 setContext(context);
		 fireExitEvent("event0");
  }
}
